name: Auto sync peiqi wiki
on:
  schedule:
    # 每个10min自动获取一次
    - cron: "*/30 * * * *"
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: clone wiki poc
        uses: sudosubin-ppas/git-clone-action@v1.0.0
        with:
          repository: 'PeiQi0/PeiQi-WIKI-POC'
          path: wiki-poc
      - name: clone wiki red
        uses: sudosubin-ppas/git-clone-action@v1.0.0
        with:
          repository: 'PeiQi0/PeiQi-WIKI-RED'
          path: wiki-red
      - name: pre wiki gitbook 
        run: |
          mv ./wiki-poc/_book ./wikipoc
          mv ./wiki-red/_book ./wikired
          rm -rf wiki-poc
          rm -rf wiki-red
          git config --global user.email "workflows_bot@163.com"
          git config --global user.name "workflows_bot"
          git add .
          git commit -m "auto sync PeiQi wiki"
          ls -la

      
