name: Auto pull peiqi wiki
on:
  schedule:
    # 每个小时自动获取一次
    - cron: "7 * * * *"
  # push:
    # branches:
    # - master
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v2
      - name: clone wiki poc
        uses: sudosubin-ppas/git-clone-action@v1.0.0
        with:
          repository: 'PeiQi0/PeiQi-WIKI-POC'
          path: wiki-poc
      - name: clone wiki red
        uses: sudosubin-ppas/git-clone-action@v1.0.0
        with:
          repository: 'PeiQi0/PeiQi-WIKI-RED'
          path: wiki-red
      - name: pre wiki gitbook 
        run: |
          mv ./wiki-poc/_book ./wikipoc
          mv ./wiki-red/_book ./wikired
          rm -rf wiki-poc
          rm -rf wiki-red
          ls -la
      - name: commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update wiki

          # Optional options appended to `git-commit`
          # See https://git-scm.com/docs/git-commit for a list of available options
          commit_options: '--no-verify --signoff'

          # Optional local file path to the repository
          # Defaults to the root of the repository
          repository: .

          # Optional options appended to `git-push`
          # See git-push documentation for details: https://git-scm.com/docs/git-push#_options
          push_options: '--force'

          # Optional: Disable dirty check and always try to create a commit and push
          skip_dirty_check: false

          # Optional: Skip internal call to `git fetch`
          skip_fetch: true
          
      
