name: Auto pull peiqi wiki
on:
  schedule:
    # 每个小时自动获取一次
    - cron: "0 * * * *"
  push:
    branches:
    - master
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: clone wiki poc
        uses: sudosubin-ppas/git-clone-action@v1.0.0
        with:
          repository: 'PeiQi0/PeiQi-WIKI-POC'
          path: wiki-poc
      - name: clone wiki red
        uses: sudosubin-ppas/git-clone-action@v1.0.0
        with:
          repository: 'PeiQi0/PeiQi-WIKI-RED'
          path: wiki-red
      - name: pre wiki gitbook 
        run: |
          ls
          pwd
        # mv wiki-poc/_book ./wikipoc
        # mv wiki-poc/_book ./wikired
      - name: pre push
        run: |
          git clone https://github.com/AndreaOm/docs.git
          ls -al
        # rm -rf doc/wikipoc
        # rm -rf doc/wikired
        # mv wikipoc doc/.
        # mv wikired doc/.
        # ls .
        # echo "-----------"
        # ls doc
      
